template: containers
configuration:
  Cloud:
    Profile: ""
    Provider: ""
  Containers:
  - Environment: {}
    Image: gcr.io/instruqt/php-ide:latest
    Name: shell
    Ports:
      - 6800
    Resources:
      Memory: 128
    Shell: /bin/bash
