#!/bin/bash

set-workdir $DIRECTORY

cd /projects/code

result=$(echo $(php index.php) | awk '{print tolower($0)}')

if [ "$result" != "hello world" ]; then
	fail-message "Your challenge failed because the text you echo ($(php index.php)) doesn't match (Hello World)";
	exit 1;
fi

exit 0;
