#!/bin/bash
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.

set-workdir $DIRECTORY

result=$(echo $(php index.php) | awk '{print tolower($0)}')

if [ "$result" != "hello world" ]; then
	fail-message "Your challenge failed because the text you echo ($(php index.php)) doesn't match (Hello World)";
	exit 1;
fi

exit 0;
