#!/bin/bash
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#
set-workdir $DIRECTORY

result=$(php index.php)

if [[ !${result,,} = "hello world" ]]; then
	fail-message "Your challenge failed because the text you echo (${result}) doesn't look like Hello World";
	exit 1;
fi

echo 0;